<a href="https://colab.research.google.com/github/anihc1978/python-warmup/blob/feature%2Fnumpy-warmup-exercises/numpy_warmup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Exercise 1: Create a 5x5 matrix of random numbers
rng = np.random.default_rng(42)
matrix = rng.random((5, 5))
print("Exercise 1: 5x5 random matrix")
print(matrix)

Exercise 1: 5x5 random matrix
[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
 [0.97562235 0.7611397  0.78606431 0.12811363 0.45038594]
 [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142 ]
 [0.22723872 0.55458479 0.06381726 0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835 ]]


In [ ]:
# Exercise 2: Normalize each column to mean 0 / std 1 (z-score normalization)
col_means = matrix.mean(axis=0)
col_stds = matrix.std(axis=0)
normalized = (matrix - col_means) / col_stds
print("Exercise 2: Column-normalized matrix")
print(normalized)
print("\nColumn means (should be ~0):", normalized.mean(axis=0).round(10))
print("Column stds  (should be ~1):", normalized.std(axis=0).round(10))

Exercise 2: Column-normalized matrix
[[ 0.55028404 -0.80095105  0.60892582  0.08414418 -1.68019772]
 [ 1.2764785   0.73270895  0.38124538 -1.94817011 -0.12737519]
 [-0.90147621  1.52092928 -0.06511281  0.53181604 -0.15776714]
 [-1.41842906 -0.25029784 -1.88586245  0.54920101  0.66287324]
 [ 0.49314273 -1.20238934  0.96080406  0.78300889  1.3024668 ]]

Column means (should be ~0): [ 0.  0.  0. -0.  0.]
Column stds  (should be ~1): [1. 1. 1. 1. 1.]


In [ ]:
# Exercise 3: Compute pairwise Euclidean distances between rows
# Use broadcasting: ||a - b||^2 = ||a||^2 + ||b||^2 - 2*a.b
sq_sum = np.sum(matrix ** 2, axis=1, keepdims=True)  # (5,1)
dot_prod = matrix @ matrix.T                          # (5,5)
dist_matrix = np.sqrt(np.maximum(0, sq_sum + sq_sum.T - 2 * dot_prod))
print("Exercise 3: Pairwise Euclidean distance matrix (5x5)")
print(dist_matrix.round(4))

Exercise 3: Pairwise Euclidean distance matrix (5x5)
[[0.     0.7751 0.7644 1.118  0.7255]
 [0.7751 0.     0.9466 1.2832 0.9693]
 [0.7644 0.9466 0.     0.7287 0.8375]
 [1.118  1.2832 0.7287 0.     1.0817]
 [0.7255 0.9693 0.8375 1.0817 0.    ]]


In [ ]:
# Exercise 4: Mask all values below the median (set them to NaN)
med = np.median(matrix)
masked = matrix.copy().astype(float)
masked[masked < med] = np.nan
print("Exercise 4: Matrix with below-median values masked (NaN)")
print(f"Median value: {med:.4f}")
print(masked)

Exercise 4: Matrix with below-median values masked (NaN)
Median value: 0.6974
[[0.77395605        nan 0.85859792 0.69736803        nan]
 [0.97562235 0.7611397  0.78606431        nan        nan]
 [       nan 0.92676499        nan 0.82276161        nan]
 [       nan        nan        nan 0.82763117        nan]
 [0.75808774        nan 0.97069802 0.89312112 0.7783835 ]]


In [ ]:
# Exercise 5: Vectorize a function that converts Celsius to Fahrenheit
def celsius_to_fahrenheit_scalar(c):
    return c * 9/5 + 32

    # Vectorize using np.vectorize
    celsius_to_fahrenheit = np.vectorize(celsius_to_fahrenheit_scalar)

    celsius_vals = np.array([-40, -20, 0, 20, 37, 100])
    fahrenheit_vals = celsius_to_fahrenheit(celsius_vals)
    print("Exercise 5: Vectorized Celsius -> Fahrenheit")
    for c, f in zip(celsius_vals, fahrenheit_vals):
        print(f"  {c:>5}°C = {f:>7.2f}°F")

In [ ]:
# Exercise 6: Reshape a 1D array of 100 values into 10x10
arr_1d = np.arange(100)
reshaped = arr_1d.reshape(10, 10)
print("Exercise 6: 1D array of 100 values reshaped to 10x10")
print(f"Original shape: {arr_1d.shape}")
print(f"New shape:      {reshaped.shape}")
print(reshaped)

Exercise 6: 1D array of 100 values reshaped to 10x10
Original shape: (100,)
New shape:      (10, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
# Exercise 7: Compute a rolling mean with stride using stride_tricks
data = np.arange(1, 21, dtype=float)  # [1, 2, ..., 20]
window = 4
stride = 2

# Use stride_tricks to create sliding window view
from numpy.lib.stride_tricks import sliding_window_view
windows = sliding_window_view(data, window_shape=window)[::stride]
rolling_mean = windows.mean(axis=1)

print("Exercise 7: Rolling mean (window=4, stride=2)")
print(f"Input data:   {data}")
print(f"Rolling means: {rolling_mean}")

Exercise 7: Rolling mean (window=4, stride=2)
Input data:   [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
Rolling means: [ 2.5  4.5  6.5  8.5 10.5 12.5 14.5 16.5 18.5]


In [ ]:
# Exercise 8: One-hot encode an integer array
integer_array = np.array([0, 2, 1, 0, 3])
num_classes = integer_array.max() + 1
one_hot = np.eye(num_classes, dtype=int)[integer_array]
print("Exercise 8: One-hot encoding")
print(f"Integer array: {integer_array}")
print(f"Num classes:   {num_classes}")
print("One-hot encoded:")
print(one_hot)

Exercise 8: One-hot encoding
Integer array: [0 2 1 0 3]
Num classes:   4
One-hot encoded:
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 1]]


In [ ]:
# Exercise 9: Concatenate two arrays along axis 0 then axis 1
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concat_axis0 = np.concatenate((arr1, arr2), axis=0)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)

print("Exercise 9: Array concatenation")
print(f"Array 1:\n{arr1}")
print(f"Array 2:\n{arr2}")
print(f"\nConcatenated along axis 0 (rows):\n{concat_axis0}")
print(f"\nConcatenated along axis 1 (columns):\n{concat_axis1}")

Exercise 9: Array concatenation
Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]

Concatenated along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Exercise 10: Replace all negative values with 0 (ReLU)
rng2 = np.random.default_rng(99)
array_with_neg = rng2.standard_normal((4, 5))  # values in ~[-3, 3]
relu_result = np.maximum(0, array_with_neg)
print("Exercise 10: Replace negative values with 0 (ReLU)")
print("Original array:")
print(array_with_neg.round(3))
print("\nAfter replacing negatives with 0:")
print(relu_result.round(3))
print(f"\nNegative values before: {(array_with_neg < 0).sum()}")
print(f"Negative values after:  {(relu_result < 0).sum()}")

Exercise 10: Replace negative values with 0 (ReLU)
Original array:
[[ 0.082 -0.464  0.051  0.686 -1.757]
 [ 1.684 -0.458 -0.596 -1.047  0.932]
 [ 0.675  1.244  0.893  0.263  0.329]
 [ 0.935 -0.878 -0.046  0.382 -0.453]]

After replacing negatives with 0:
[[0.082 0.    0.051 0.686 0.   ]
 [1.684 0.    0.    0.    0.932]
 [0.675 1.244 0.893 0.263 0.329]
 [0.935 0.    0.    0.382 0.   ]]

Negative values before: 8
Negative values after:  0
